### ISSUE TITLE
Почему сайт перестал работать?

### ISSUE THREAD

**Issue by wmean-spec** [RedMaun/quote-site#3]
Захожу на [redmaun.site](redmaun.site), а там Error 502, Host Error

**Comment by RedMaun** [comment]
Достопочтенный Евгений Рыбин, приношу извинения за данную оплошность. Видите ли, сайт(ы) упали, а поднять я их не могу, а все потому что я переустановил windows 10 home edition на своем ноутбуке, что в свою очередь удалило мой ssh ключ. Ну короче нахуй иди понял да.
